### ISSUE TITLE
Issue with Tests

### ISSUE THREAD

**Issue by annafractuous** [learn-co-curriculum/my-each#11]
The tests pass both when the yield argument is the current element and when it is the element's index. I.e. both these methods pass all tests:

def my_each(array)
  i = 0
  while i < array.length 
    yield(array[i])
    i += 1
  end
  array
end

def my_each(array)
  i = 0
  while i < array.length 
    yield i 
    i += 1
  end
  array
end

**Comment by SophieDeBenedetto** [comment]
hi @annafractuous, thanks for pointing this out. The test has just been updated to be more rigorous.
