### ISSUE TITLE
It's easy to fool 7/8 of the spec tests by a simple 'puts' instead of yield.

### ISSUE THREAD

**Issue by mikeappell** [learn-co-curriculum/my-each#13]
I was answering a student's question, and it came up that 7/8 of the spec tests were being passed without even needing to use the keyword with code along these lines:

def my_each(array)
  counter = 0
  while counter < array.length do
    puts "hello"
    counter += 1
  end
  return array
end

It might be worth making the spec tests more specific to the yield keyword for the various labs in this section.

**Comment by AnnJohn** [comment]
@SophieDeBenedetto Can you look into this? Thanks

**Comment by SophieDeBenedetto** [comment]
hi @mikeappell, 

I added one more test to see that users are not using `while` or `puts`. Some tests will pass if students use those keywords but in order to get all tests passing you will need to use `yield` correctly. Added note to that effect.

**Comment by mikeappell** [comment]
Awesome. Thanks all!
