### ISSUE TITLE
Warning messages when I run 'learn' - please see comment below for entire learn output

### ISSUE THREAD

**Issue by beingy** [learn-co-curriculum/my-each#25]
/home/beingy/code/labs/my-each-v-000/spec/my_each_spec.rb:61: warning: assigned but unused variable - tas_original
/home/beingy/code/labs/my-each-v-000/spec/my_each_spec.rb:105: warning: assigned but unused variable - expected
/home/beingy/code/labs/my-each-v-000/spec/my_each_spec.rb:106: warning: assigned but unused variable - times_called
/usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54: warning: loading in progress, circular require considered harmful - /usr/local/rvm/gems/ruby-2.2.3/gems/pry-0.10.3/lib/pry.rb
	from /usr/local/rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in  `<main>'
	from /usr/local/rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in  `eval'
	from /usr/local/rvm/gems/ruby-2.2.3/bin/rspec:23:in  `<main>'
	from /usr/local/rvm/gems/ruby-2.2.3/bin/rspec:23:in  `load'
	from /usr/local/rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.4/exe/rspec:4:in  `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:45:in  `invoke'
	from /usr/local/rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:78:in  `run'
	from /usr/local/rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:92:in  `run'
	from /usr/local/rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:106:in  `setup'
	from /usr/local/rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1359:in  `load_spec_files'
	from /usr/local/rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1359:in  `each'
	from /usr/local/rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1361:in  `block in load_spec_files'
	from /usr/local/rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1361:in  `load'
	from /home/beingy/code/labs/my-each-v-000/spec/my_each_spec.rb:2:in  `<top (required)>'
	from /usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in  `require'
	from /usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in  `rescue in require'
	from /usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in  `require'
	from /usr/local/rvm/gems/ruby-2.2.3/gems/pry-0.10.3/lib/pry.rb:150:in  `<top (required)>'
	from /usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in  `require'
	from /usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in  `require'
	from /usr/local/rvm/gems/ruby-2.2.3/gems/pry-0.10.3/lib/pry/cli.rb:107:in  `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.2.3/gems/pry-0.10.3/lib/pry/cli.rb:39:in  `add_plugin_options'
	from /usr/local/rvm/gems/ruby-2.2.3/gems/pry-0.10.3/lib/pry/cli.rb:39:in  `each'
	from /usr/local/rvm/gems/ruby-2.2.3/gems/pry-0.10.3/lib/pry/cli.rb:40:in  `block in add_plugin_options'
	from /usr/local/rvm/gems/ruby-2.2.3/gems/pry-0.10.3/lib/pry/plugins.rb:38:in  `load_cli_options'
	from /usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in  `require'
	from /usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in  `require'
	from /usr/local/rvm/gems/ruby-2.2.3/gems/pry-nav-0.2.4/lib/pry-nav/cli.rb:1:in  `<top (required)>'
	from /usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in  `require'
	from /usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in  `rescue in require'
	from /usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in  `require'
	from /usr/local/rvm/gems/ruby-2.2.3/gems/pry-nav-0.2.4/lib/pry-nav.rb:2:in  `<top (required)>'
	from /usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in  `require'
	from /usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in  `require'
	from /usr/local/rvm/gems/ruby-2.2.3/gems/pry-nav-0.2.4/lib/pry-nav/pry_ext.rb:1:in  `<top (required)>'
	from /usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in  `require'
	from /usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in  `require'
/usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54: warning: loading in progress, circular require considered harmful - /usr/local/rvm/gems/ruby-2.2.3/gems/pry-0.10.3/lib/pry.rb
	from /usr/local/rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in  `<main>'
	from /usr/local/rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in  `eval'
	from /usr/local/rvm/gems/ruby-2.2.3/bin/rspec:23:in  `<main>'
	from /usr/local/rvm/gems/ruby-2.2.3/bin/rspec:23:in  `load'
	from /usr/local/rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.4/exe/rspec:4:in  `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:45:in  `invoke'
	from /usr/local/rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:78:in  `run'
	from /usr/local/rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:92:in  `run'
	from /usr/local/rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:106:in  `setup'
	from /usr/local/rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1359:in  `load_spec_files'
	from /usr/local/rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1359:in  `each'
	from /usr/local/rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1361:in  `block in load_spec_files'
	from /usr/local/rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1361:in  `load'
	from /home/beingy/code/labs/my-each-v-000/spec/my_each_spec.rb:2:in  `<top (required)>'
	from /usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in  `require'
	from /usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in  `rescue in require'
	from /usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in  `require'
	from /usr/local/rvm/gems/ruby-2.2.3/gems/pry-0.10.3/lib/pry.rb:150:in  `<top (required)>'
	from /usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in  `require'
	from /usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in  `require'
	from /usr/local/rvm/gems/ruby-2.2.3/gems/pry-0.10.3/lib/pry/cli.rb:107:in  `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.2.3/gems/pry-0.10.3/lib/pry/cli.rb:39:in  `add_plugin_options'
	from /usr/local/rvm/gems/ruby-2.2.3/gems/pry-0.10.3/lib/pry/cli.rb:39:in  `each'
	from /usr/local/rvm/gems/ruby-2.2.3/gems/pry-0.10.3/lib/pry/cli.rb:40:in  `block in add_plugin_options'
	from /usr/local/rvm/gems/ruby-2.2.3/gems/pry-0.10.3/lib/pry/plugins.rb:38:in  `load_cli_options'
	from /usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in  `require'
	from /usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in  `require'
	from /usr/local/rvm/gems/ruby-2.2.3/gems/pry-nav-0.2.4/lib/pry-nav/cli.rb:1:in  `<top (required)>'
	from /usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in  `require'
	from /usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in  `rescue in require'
	from /usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in  `require'
	from /usr/local/rvm/gems/ruby-2.2.3/gems/pry-nav-0.2.4/lib/pry-nav.rb:2:in  `<top (required)>'
	from /usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in  `require'
	from /usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in  `require'
	from /usr/local/rvm/gems/ruby-2.2.3/gems/pry-nav-0.2.4/lib/pry-nav/pry_ext.rb:2:in  `<top (required)>'
	from /usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in  `require'
	from /usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in  `require'
	from /usr/local/rvm/gems/ruby-2.2.3/gems/pry-nav-0.2.4/lib/pry-nav/tracer.rb:1:in  `<top (required)>'
	from /usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in  `require'
	from /usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in  `require'
/usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54: warning: loading in progress, circular require considered harmful - /usr/local/rvm/gems/ruby-2.2.3/gems/pry-0.10.3/lib/pry.rb
	from /usr/local/rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in  `<main>'
	from /usr/local/rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in  `eval'
	from /usr/local/rvm/gems/ruby-2.2.3/bin/rspec:23:in  `<main>'
	from /usr/local/rvm/gems/ruby-2.2.3/bin/rspec:23:in  `load'
	from /usr/local/rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.4/exe/rspec:4:in  `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:45:in  `invoke'
	from /usr/local/rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:78:in  `run'
	from /usr/local/rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:92:in  `run'
	from /usr/local/rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.4/lib/rspec/core/runner.rb:106:in  `setup'
	from /usr/local/rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1359:in  `load_spec_files'
	from /usr/local/rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1359:in  `each'
	from /usr/local/rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1361:in  `block in load_spec_files'
	from /usr/local/rvm/gems/ruby-2.2.3/gems/rspec-core-3.4.4/lib/rspec/core/configuration.rb:1361:in  `load'
	from /home/beingy/code/labs/my-each-v-000/spec/my_each_spec.rb:2:in  `<top (required)>'
	from /usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in  `require'
	from /usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in  `rescue in require'
	from /usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in  `require'
	from /usr/local/rvm/gems/ruby-2.2.3/gems/pry-0.10.3/lib/pry.rb:150:in  `<top (required)>'
	from /usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in  `require'
	from /usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in  `require'
	from /usr/local/rvm/gems/ruby-2.2.3/gems/pry-0.10.3/lib/pry/cli.rb:107:in  `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.2.3/gems/pry-0.10.3/lib/pry/cli.rb:39:in  `add_plugin_options'
	from /usr/local/rvm/gems/ruby-2.2.3/gems/pry-0.10.3/lib/pry/cli.rb:39:in  `each'
	from /usr/local/rvm/gems/ruby-2.2.3/gems/pry-0.10.3/lib/pry/cli.rb:40:in  `block in add_plugin_options'
	from /usr/local/rvm/gems/ruby-2.2.3/gems/pry-0.10.3/lib/pry/plugins.rb:38:in  `load_cli_options'
	from /usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in  `require'
	from /usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in  `require'
	from /usr/local/rvm/gems/ruby-2.2.3/gems/pry-nav-0.2.4/lib/pry-nav/cli.rb:1:in  `<top (required)>'
	from /usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in  `require'
	from /usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in  `rescue in require'
	from /usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in  `require'
	from /usr/local/rvm/gems/ruby-2.2.3/gems/pry-nav-0.2.4/lib/pry-nav.rb:3:in  `<top (required)>'
	from /usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in  `require'
	from /usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in  `require'
	from /usr/local/rvm/gems/ruby-2.2.3/gems/pry-nav-0.2.4/lib/pry-nav/commands.rb:1:in  `<top (required)>'
	from /usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in  `require'
	from /usr/local/rvm/rubies/ruby-2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in  `require'

my_each
  does not call on each
  does not call on puts
  calls on while
  iterates over each element
  yields the correct element
  can handle an empty collection
  returned array contains the same elements as the original collection
  does not modify the original collection
  block is run n times
  only single element is passed into block

Finished in 0.01507 seconds (files took 0.72076 seconds to load)
10 examples, 0 failures

**Comment by AnnJohn** [comment]
hi @beingy, because this looks like an issue specific to you can you use the Ask a Question feature? Someone from our team will get back to you right away there. Thanks!
