### ISSUE TITLE
Error with Rspec File Test

### ISSUE THREAD

**Issue by amjack59** [learn-co-curriculum/my-each#26]
After running learn against my code for this lab I received the following errors indicating a problem in the Rspec tests : /home/amjack59/code/labs/my-each-v-000/spec/my_each_spec.rb:61: warning: assigne
d but unused variable - tas_original                                            
/home/amjack59/code/labs/my-each-v-000/spec/my_each_spec.rb:105: warning: assign
ed but unused variable - expected                                               
/home/amjack59/code/labs/my-each-v-000/spec/my_each_spec.rb:106: warning: assign
ed but unused variable - times_called  

Would you please look into this and let me know how to proceed. Thanks.

**Comment by AnnJohn** [comment]
hi @amjack59 sorry for the delay. since this looks like an issue specific to your code could you please use the Ask a Question tool and someone from our team will get back to you one-on-one? Thanks!
