### ISSUE TITLE
I'm not sure this RSpec test is actually testing for anything

### ISSUE THREAD

**Issue by ga-be** [learn-co-curriculum/my-each#28]
I can't think of a situation in which the below invocation of `#my_each(tas) do |ta| end` could possibly modify the variable `tas` within this RSpec test:
```ruby
it "does not modify the original collection" do
    tas = ['arel', 'jon', 'logan', 'spencer']
    # array may be modified by the iteration function so
    # we cannot use it for verifying the results
    # therefore we create a new copy using the clone method
    tas_original = tas.clone

    # run the method
    my_each(tas) do |ta|
      # Do nothing on yield
    end

    # is verifying if the array we passed to method
    # has not been modified
    expect(tas).to eq(tas_original)
end
```

**Comment by pletcher** [comment]
Thanks for opening this issue!

Keep in mind that this space is for specific issues related to the content of this lesson.

If you're reporting on the content of this lesson, it'd be super helpful if you could include a stack trace of any errors that you're seeing.

If you'd like to report a bug about the Learn IDE, the Ask a Question form, opening a file, or the lights not working on Learn, please report a bug directly on https://learn.co. (You can find the bug report form by clicking on your avatar in the upper right, and then selecting "Report A Bug".)

Please be sure to include steps to reproduce (be as detailed as possible) and any relevant information about your environment. (Are you using the Learn IDE? Coding on a refurbished toaster?) We'll be sure to figure out what's going on — and to jump in and help — just as soon as we can. Thanks!
