### ISSUE TITLE
The instructions to this lab are misleading

### ISSUE THREAD

**Issue by cdudhat** [learn-co-curriculum/my-each#29]
The instructions ask to create an "each" like method using "while" and "yield". For the example, it shows a method that "puts" each element and then expects to receive the array itself in return. Whereas, that is not possible without calling out the method itself again. And the tests are passing without actually using  "puts" anywhere.
![screen shot 2016-09-12 at 9 23 00 pm](https://cloud.githubusercontent.com/assets/18668942/18458539/bfc0da28-792f-11e6-9567-b13be66be7ac.png)
![screen shot 2016-09-12 at 9 23 38 pm](https://cloud.githubusercontent.com/assets/18668942/18458542/c3a2c91c-792f-11e6-8443-baf204e4ed62.png)
![screen shot 2016-09-12 at 9 24 05 pm](https://cloud.githubusercontent.com/assets/18668942/18458545/c61433fc-792f-11e6-968c-13d1be284498.png)

**Comment by sgharms** [comment]
I think you might not _quite_ be fully understanding the way this code is
working. I was able to meet the specifications without doubly calling the method.

Try discussing your issue via the [Ask a Question][AAQ] tool. You're
close, so stick with it!

[AAQ]: http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson
