### ISSUE TITLE
My_Each - confusing instructions

### ISSUE THREAD

**Issue by KellyStamps** [learn-co-curriculum/my-each#30]
I'd just like to send some feedback on this lab - I found the instructions incredibly confusing. The lab says "Here's an example of what should happen when you call your my_each method: 
collection = [1, 2, 3, 4]
my_each(collection) do |i|
  puts i
end"
That led me to believe that the correct way to complete the lab was to use puts. The tests themselves were also confusing, and it took a long to understand that all that was required was to execute the block, not produce an output.

I would suggest to change the example, or clarify that the end result will NOT be printing anything out.

**Comment by sgharms** [comment]
Thank you for your feedback. If your code works with `puts` inside the block, it will work with any arbitrary code – that's the magic of `yield`!

I welcome you to [Ask a Question][AAQ]. Based on this issue you're right on the edge of an amazing "WHOA" moment, I hope you take the plunge!

[AAQ]: http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson
