### ISSUE TITLE
Just yield.

### ISSUE THREAD

**Issue by BenitolSantos** [learn-co-curriculum/my-each#32]
In the previous section (the section right before) _yield and blocks_, yield is taught by being put after the method is called with do or {}. But according to the technical coach who helped me, (Marcel Galang) didn't like me putting do or {} after the method was called. All I had to do was put yield anywhere in the method. And nothing after it was called. Then he told me I was overthinking it pass the tests and move on. Which made no sense because I was taught a certain way how yield works. I guess maybe this should be placed after _return from yield statements_.

**Comment by sgharms** [comment]
I believe you're describing a solution issues. The purpose of issues here is to catch bugs and problems in the code as given.

If you need help understanding style options, try using [AAQ](http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson). 

If, after reviewing your code and consulting AAQ, you still feel that this is an issue with the curriculum itself, please reopen the issue and provide more detail about why it's a curriculum issue, the steps needed to reproduce the issue, and any additional relevant information about your development environment.
