### ISSUE TITLE
difficulty understanding yield

### ISSUE THREAD

**Issue by markedwardmurray** [learn-co-curriculum/my-each#7]
I solved the lab eventually, but I still don't feel like I really understand how to use each. In part, I think i'm still confused about blocks/enclosures in Ruby. Granted, that's a pretty complex topic that iOS doesn't touch until week 6 or so. Just felt like I really struggled accomplishing this lab. I'm sorry I can't give very specific advice about how to improve the lesson at this point.

@SophieDeBenedetto

**Comment by SophieDeBenedetto** [comment]
This is a tough lab and the concept of yield is a bit advanced. I'm comfortable marking this lab as advanced for the time being. It is important to understand how to use each/why, not so much how it works. Is the basic `.each` method still unclear?

**Comment by markedwardmurray** [comment]
I get how to use the iteration methods like .each at this point. I'm getting better with `yield` after solving `my_collect`. I think enclosures are more fundamental to Ruby than to iOS, so I'm not sure it's appropriate to mark it is "advanced" material.

**Comment by AnnJohn** [comment]
Iceboxing for now
