### ISSUE TITLE
RSpec passing false positives

### ISSUE THREAD

**Issue by caporta** [learn-co-curriculum/my-each#8]
As per README:

>Here's an example of what should happen when you call your my_each method:

>```Ruby
>collection = [1, 2, 3, 4]
>my_each(collection) do |i|
>  puts i
>end
>```
>This should output:
>```
>1
>2
>3
>4
>```
and return:

>`#=> [1, 2, 3, 4]`

>Just like the real .each method.

Two passing PRs in this lab's repo (commits [e7a640](https://github.com/Biletnikoff/my-each-001/commit/e7a640aa63710e2d3f901deea5bf656e5c034576) & [d9d9cd](https://github.com/ruthmesfun/my-each-001/commit/d9d9cd128aa16359ea34c78050b4b6a172b613c0)) contain variants of the following code:

```Ruby
def my_each(array) 
  while array.length > 0
    yield(array)
    array.pop
  end
  return array
end
```

which outputs:

```
1
2
3
4
1
2
3
1
2
1
=> []
```

The above code should not satisfy the parameters set forth in the README, and therefore seems to be an instance of RSpec passing a false positive.

In addition, the README instructs students to:

> ...try to write your own version of the .each method without using the `.each` method provided by Ruby.

yet a passing PR (commit [4155fb](https://github.com/AnthonyRNL/my-each-001/commit/4155fba54af724f9a649bd4eb852265f068ba15a)) utilizes `.each` within `my_each`. This seems like another instance of RSpec passing a false positive, and including another test to prevent this in the future may be an appropriate solution.

**Comment by AnnJohn** [comment]
Thanks @caporta for raising the issue. I think the same problem has been raised in previous issues so if that's the case with an issue, could you add your awesome explanation as a comment in an existing, open issue so that we can minimize the number of issues. If I'm wrong and this is a new, different issue, then sorry and thanks for raising! I'm going to icebox it for now and we'll get to it when we review this lab in our larger curriculum review process.

**Comment by caporta** [comment]
@AnnJohn These issues don't seem to have been raised previously (I reread all open and closed issues to be sure). As far as I can see, they should remain a unique open issue.

**Comment by AnnJohn** [comment]
@caporta Great, sounds good and thanks. I'll put it on icebox for now and will reopen it when we  get to updating this specific lab which should be within the next couple of weeks.
